ATLASSIAN_BASE_URL = "https://godaddy-corp.atlassian.net/"
ATLASSIAN_EMAIL = "@godaddy.com"
ATLASSIAN_API_TOKEN = ""
DEFAULT_SPACE = "IMA"
DEFAULT_CONTENT_TYPES = "page,blogpost"
GITHUB_TOKEN = ""
GITHUB_DEFAULT_ORG = "godaddy"
GITHUB_DEFAULT_REPO = ""
SP_TENANT_ID     = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
SP_CLIENT_ID     = "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy"
SP_CLIENT_SECRET = "YOUR_APP_CLIENT_SECRET"
SP_DEFAULT_SITE  = ""
AGENT_API_TOKEN=""
AGENT_CONVERSATION_ID=""
AGENT_ID=""
GOCAAS_API_TOKEN="